services:
  # Backend Service
  - type: web
    name: chatapp-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chatapp-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://chatapp-frontend.onrender.com
      - key: PORT
        value: 3000
    healthCheckPath: /

  # Frontend Service
  - type: web
    name: chatapp-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://chatapp-backend.onrender.com
      - key: VITE_SOCKET_URL
        value: https://chatapp-backend.onrender.com

databases:
  - name: chatapp-db
    plan: free
    region: oregon
